# Generated by Django 4.2.30 on 2026-05-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0005_recipe_favorited_by_alter_recipe_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipeApp.category'),
        ),
    ]
