# Generated by Django 6.0.2 on 2026-05-14 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0006_recipe_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
    ]
